# Site settings
title: ideaapps
description: ideaapps|mobile|android|ios|swift|native|software development

# User settings
username: ideaapps
user_description: TODO
user_title: Mobile native development
email: marcin.polak@ideaapps.io
github_username: polok

# Google-analytics
google-analytics:
  id: "UA-96457755-1"

exclude: ['package.json', 'src' , 'node_modules']
